### ISSUE TITLE
[BUG] demo not working right now

### ISSUE THREAD

**Issue by aloshai** [lukasbach/monaco-editor-auto-typings#10]
**Describe the bug**
The demo version you have published does not work.

**Expected behavior**
React, express or any package types does not pulling. Even not working with default draft. 

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/39468199/162509158-45f90888-8eb0-4933-9ece-cd7fcc866298.png)
![image](https://user-images.githubusercontent.com/39468199/162510364-8ea1bdf3-fafe-489a-be89-acf6a74347a3.png)

- OS: Windows 11
- Browser Version: Microsoft Edge 100.0.1185.29
- `monaco-editor-auto-typings` Version: v0.3.1

**Comment by lukasbach** [comment]
Hi @aloshai, thanks for the report! I pushed a fix, it should be working again. You might need to clear the browser cache, at least for me that was necessary to get the latest JS files in the browser.

**Comment by aloshai** [comment]
yes, it is working now. thanks! @lukasbach
