### ISSUE TITLE
Monaco seemingly not working

### ISSUE THREAD

**Issue by dolanmiu** [lukasbach/monaco-editor-auto-typings#15]
After doing everything correctly, sometimes it's worth explicitly adding `monaco` into the config, as it could take another instance of `monaco` (this is what happened to me with my set up):

```ts
this.autoTypings = await AutoTypings.create(this.editor, {
      monaco,
      sourceCache: storage, // Cache loaded sources in localStorage. May be omitted
    });
```

**Comment by lukasbach** [comment]
Sorry, I'm not sure I get your problem. By default, AutoTypings imports its own instance of monaco so you don't need to pass your own instance through, but you can if you need to, the property is supported as an option.
