### ISSUE TITLE
[BUG] Custom version is not downloaded - latest is downloaded instead

### ISSUE THREAD

**Issue by HonzaTuron** [lukasbach/monaco-editor-auto-typings#18]
**Describe the bug**
I'm using auto typings in combination with `@monaco-editor/react`, and my AutoTypings create config is following:
```
await AutoTypings.create(editor, { sourceCache: new LocalStorageCache(), monaco, versions: { apify: '2.3.2' }, preloadPackages: true });
```

So I would expect `apify@2.3.2` is downloaded, but instead, latest `apify@3.0.1` is downloaded (and cached).

**To Reproduce**
Set different major version for any package, try to fetch its types

**Expected behavior**
Different version types is fetched

**Environment (please complete the following information):**
React 17.0.2 /w CRA

- OS: macOS
- Browser Version: Chromium 103
- `monaco-editor-auto-typings` Version: `0.4.2`

**Comment by lukasbach** [comment]
Thank you for your contribution!
