### ISSUE TITLE
[REQUEST] build the file + the imported package

### ISSUE THREAD

**Issue by columnapp** [lukasbach/monaco-editor-auto-typings#24]
**Is your feature request related to a problem? Please describe.**
First off, thank you for the plugin this would cut down on the work needed for my project tremendously, thank you! This is somewhat related to the problem, after a package is "imported", how do we actually "run" / "build" it?
**Describe the solution you'd like**
After the user types for example:
```
import _ from 'lodash'
export default {
  run() {
    return _.map([1, 2], (n) => n * 2)
  }
}
```
how can I get the exported object as a javascript, bundled with lodash?
This most likely is out of scope of the plugin, I apologize if so, would love to get pointers to the right direction if you don't mind :)
**Additional context**

**Comment by lukasbach** [comment]
Hi! Neither monaco nor this library focuses on the execution of the code in the editor component. monaco-editor-auto-typings only downloads type information, e.g. .d.ts files that contain typescript declarations for imported modules, no JS runtime information. So yeah this use case would be out of scope of the library. How you import runtime data and execute it depends on your use case.

If you want to run it on a server, you could programmatically run install commands for each import and execute the code, potentially in a js vm depending on the security use case.
If you want to run it in the browser, you could load the dependencies from unpkg and execute the code in the browser with the imported symbols from there in scope.

Note that you can programmatically hook yourself into when new imports where added to the code model, to retrieve the names of the imported packags: https://lukasbach.github.io/monaco-editor-auto-typings/docs/interfaces/Options.html#onUpdateVersions
