### ISSUE TITLE
[BUG] Could not resolve @types/scheduler/tracing/index.d.ts

### ISSUE THREAD

**Issue by wangzongming** [lukasbach/monaco-editor-auto-typings#5]
**Describe the bug**
An error message appears on the console after using the plug-in：Could not resolve @types/scheduler/tracing/index.d.ts
This error also exists in the case，https://lukasbach.github.io/monaco-editor-auto-typings/#

**Comment by lukasbach** [comment]
Hello @wangzongming, can you please provide me the code you inserted into the editor that caused this error (or the package you imported in the editor)?

**Comment by wangzongming** [comment]
Hello @lukasbach , 
I used the following packages

`import { AutoTypings, LocalStorageCache } from 'monaco-editor-auto-typings';`


This is the code when I call it
```
AutoTypings.create(editor.current, {
	sourceCache: new LocalStorageCache(),
	shareCache: false
});
```

There's just a warning on the console. The examples provided above also have this warning
https://lukasbach.github.io/monaco-editor-auto-typings/#
![image](https://user-images.githubusercontent.com/27466569/147801135-c0602559-ad97-4bba-b20b-121be7e54a9b.png)

**Comment by lukasbach** [comment]
Ah I didn't realize it was an issue with the live code. Thanks for the details!

Looks like it tries to resolve native node packages, which are not hosted on npm. I guess this is not an urgent issue since the resolver just stops after running into the import error, but this should be fixed to ignore resolving native modules.

**Comment by wangzongming** [comment]
> 

😁dude, you're right. It's not urgent. 
 Just fix it in a future release. 
thank you

**Comment by lukasbach** [comment]
I've removed the logging for "Could not resolve..." from the console.
