### ISSUE TITLE
[FEEDBACK] Is the project still being maintained? Can support manoca 0.32.0?

### ISSUE THREAD

**Issue by Innei** [lukasbach/monaco-editor-auto-typings#8]
Hi, I use this package copy demo source code work well in monaco 0.26.x, but it too old, and upgrade monaco up to 0.32, it is not working. Can you upgrade dependency and fix it? Thanks.

**Comment by lukasbach** [comment]
Hi, sorry, had some busy months and no time to look for this package. v0.2.0 of monaco-editor-auto-typings is now deployed and should handle the latest version of monaco.
